/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package TokoSepatu;

import java.awt.Frame;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author irfan
 */
public class EditBarang extends javax.swing.JDialog {
    private Connection koneksi;
    private Statement perintah;
    private ResultSet rs;
    private String idSepatu;
    private String merekSepatu;
    private String jenisSepatu;
    private String ukSepatu;
    private String stok;
    private String hargaJual;
    private DefaultTableModel model;
    /**
     * Creates new form KelolaDataJurusan
     */
    public EditBarang(Frame parent, boolean modal, String idSepatu, DefaultTableModel model) {
        
        super(parent, modal);
        initComponents();
        this.idSepatu = idSepatu;
        this.model = model;
        setLocationRelativeTo(null);
        
        // Mengatur DocumentFilter untuk jTextField4
        AbstractDocument doc4 = (AbstractDocument) jTextField4.getDocument();
        doc4.setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr)
                    throws BadLocationException {
                // Hanya izinkan input berupa angka
                if (string.matches("\\d+")) {
                    super.insertString(fb, offset, string, attr);
                }
            }
            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                // Hanya izinkan penggantian dengan input berupa angka
                if (text.matches("\\d+")) {
            super.replace(fb, offset, length, text, attrs);
                }
            }
        });
        // Mengatur DocumentFilter untuk jTextField5
        AbstractDocument doc5 = (AbstractDocument) jTextField5.getDocument();
        doc5.setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr)
                    throws BadLocationException {
                // Hanya izinkan input berupa angka
                if (string.matches("\\d+")) {
                    super.insertString(fb, offset, string, attr);
                }
            }
            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                // Hanya izinkan penggantian dengan input berupa angka
                if (text.matches("\\d+")) {
            super.replace(fb, offset, length, text, attrs);
                }
            }
        });
        
        try {
            // Step 1 : Registrasi atau Load JDBC Driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            // Step 2 : Cipatakan dan bangun koneksi ke database "polnep"
            String url = "jdbc:mysql://localhost/toko_sepatu";
            String user = "root";
            String password = "";
            koneksi = DriverManager.getConnection(url, user, password);
            // Step 3 : Ciptakan Statement
            perintah = koneksi.createStatement();
    } catch (ClassNotFoundException e) {
            System.err.println("JDBC Driver tidak ditemukan");
    } catch (SQLException e) {
            System.out.println("Gagal koneksi atau menciptakan objek statement");
    }    
    }
    
    public void editData() {

        try {
        String query = "SELECT * FROM barang "
                + "WHERE id_sepatu = '" + idSepatu + "' ";
        rs = perintah.executeQuery(query);
        while (rs.next()) {
            this.merekSepatu = rs.getString("merk_sepatu");
            this.jenisSepatu = rs.getString("jenis_sepatu");
            this.ukSepatu = rs.getString("uk_sepatu");
            this.stok = rs.getString("stok");
            this.hargaJual = rs.getString("harga_jual");
        }
    } catch (SQLException e) {
        System.err.println("Query Error");
    }
    }
    
    public void refreshData() {
        Barang.tampilData(model, jTextField1, koneksi, perintah, rs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Barang");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Merek");

        jLabel3.setText("Jenis");

        jLabel4.setText("Ukuran");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel5.setText("Stok");

        jLabel6.setText("Harga Jual");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jTextField6))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        editData();
        
        jTextField1.setEnabled(false);
        jTextField1.setText(idSepatu);
        jTextField2.setText(merekSepatu);
        jTextField3.setText(jenisSepatu);
        jTextField4.setText(ukSepatu);
        jTextField5.setText(stok);
        jTextField6.setText(hargaJual);
    }//GEN-LAST:event_formWindowOpened

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        if (jTextField4.getText().length() >= 2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(
                this, // parent, biasanya this
                "Silahkan lengkapi data Merek!", // pesannya
                "Informasi", // judul pesan
                JOptionPane.INFORMATION_MESSAGE // tipe pesan
            );
            jTextField2.requestFocus(); // fokus kursor beralih ke jTextField1
            // pengecekan apakah jTextField2 atau nama prodi belum terisi
        } else if (jTextField3.getText().equals("")) {
            // menampilkan objek JOptionPane dalam bentuk massage dialog jika
            // jTextField3 atau singkatan prodi belum terisi
            JOptionPane.showMessageDialog(
                this, // parent, biasanya this
                "Silahkan lengkapi data Jenis!", // pesannya
                "Informasi", // judul pesan
                JOptionPane.INFORMATION_MESSAGE // tipe pesan
            );
            jTextField3.requestFocus(); // fokus krusor beralih ke JTextField3
        } else if (jTextField4.getText().equals("")) {
            JOptionPane.showMessageDialog(
                this, // parent, biasanya this
                "Silahkan lengkapi data Ukuran!", // pesannya
                "Informasi", // judul pesan
                JOptionPane.INFORMATION_MESSAGE // tipe pesan
            );
            jTextField4.requestFocus();
        } else if (jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(
                this, // parent, biasanya this
                "Silahkan lengkapi data Stok!", // pesannya
                "Informasi", // judul pesan
                JOptionPane.INFORMATION_MESSAGE // tipe pesan
            );
            jTextField5.requestFocus();
        }  else if (jTextField6.getText().equals("")) {
            JOptionPane.showMessageDialog(
                this, // parent, biasanya this
                "Silahkan lengkapi data Harga Jual!", // pesannya
                "Informasi", // judul pesan
                JOptionPane.INFORMATION_MESSAGE // tipe pesan
            );
            jTextField6.requestFocus();
        } else {
            try {
                perintah.execute("UPDATE barang SET "
                        + "merk_sepatu = '" + jTextField2.getText() + "',"
                        + "jenis_sepatu = '" + jTextField3.getText() + "',"
                        + "uk_sepatu = '" + jTextField4.getText() + "',"
                        + "stok = '" + jTextField5.getText() + "',"
                        + "harga_jual = '" + jTextField6.getText()+ "'"
                        + "WHERE id_sepatu = '" + jTextField1.getText() + "' "
                    );
                    JOptionPane.showMessageDialog(
                    this, // parent, biasanya this
                    "Penyimpanan data berhasil!", // pesannya
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE // tipe pesan
                );
                refreshData();
                dispose();
            } catch (SQLException e) {
                        JOptionPane.showMessageDialog(
                            this, // parent, biasanya this
                            "Penyimpanan data Barang gagal dilakukan", // pesannya
                            "Informasi", // judul pesan
                            JOptionPane.INFORMATION_MESSAGE // tipe pesan
                        );
                    }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
